<?php


    namespace App\classes\controllers\user;


    use App\classes\abstract\ControllerEntering;
    use App\classes\models\User;
    use App\classes\utility\containers\ErrorsContainer;
    use App\classes\utility\containers\FormsWithData;
    use App\classes\utility\Registrator;
    use App\classes\utility\UserErrorsInspector;

    class Login extends ControllerEntering
    {
        protected ErrorsContainer $error;
        protected string $title = "Войти на сайт";
        protected User $candidate;
        protected FormsWithData $forms;
        protected Registrator $registrator;
        protected UserErrorsInspector $inspector;
        protected static string $action = 'loginUser';
        protected static array $checkList = ['checkEnter'];
        protected static array $errorsList = [
            'login'    => 'Введите логин',
            'password' => 'Введите пароль',
        ];

        protected function entering() : void
        {
            parent::entering(); // TODO: Change the autogenerated stub
            $this->content = $this->page->assign('candidate', $this->candidate)->assign('errors', $this->errors)->render('login');
        }
    }

