<?php

    namespace App\classes\controllers\user;

    use App\classes\abstract\ControllerEntering;
    use App\classes\models\User;
    use App\classes\utility\Registrator;
    use App\classes\utility\UserErrorsInspector;


    class Registration extends ControllerEntering
    {

        protected string $title = 'Регистрация';
        protected User $candidate;
        protected Registrator $registrator;
        protected UserErrorsInspector $inspector;
        protected static string $action = 'createNewUser';
        protected static array $checkList = ['checkEmail', 'checkLogin', 'checkPasswords'];
        protected static array $errorsList =
            [
                'login' => 'Логин отсутствует или некорректен',
                'firstName' => 'Отсутствует имя',
                'middleName' => 'Отсутствует отчество',
                'lastName' => 'Отсутствует фамилия',
                'email' => 'Не указан почтовый ящик',
                'password1' => 'Пароль отсутствует или некорректен',
                'password2' => 'Необходимо ввести повторный пароль',
            ];

        protected function entering() : void
        {
            parent::entering(); // TODO: Change the autogenerated stub
            $this->content = $this->page->assign('candidate', $this->candidate)->assign('errors', $this->errors)->render('registration');
        }
    }
