<?php

    namespace App\classes\controllers;

    use App\classes\abstract\controllers\ControllerSelector;
    use App\classes\models\User;
    use App\classes\utility\FaceControl;
    use App\traits\ControllerSelectorActionTrait;


    class Article extends ControllerSelector
    {
        private string $path = 'App\classes\controllers\article\\';

        public function __invoke()
        {
//            todo ПРОВЕРКА ПРАВ
//            if ($this->params['action'] !== 'read') {
//                if (!FaceControl::checkUserRights(User::getCurrent(), 'admin')) {
//                    Error::deadend(403, 'Нет прав доступа');
//                }
//            }
            parent::__invoke(); // TODO: Change the autogenerated stub
        }

        use ControllerSelectorActionTrait;
    }
