<?php


    namespace App\classes\controllers;


    use App\classes\abstract\Controller;
    use App\classes\Config;

    class Image extends Controller
    {
        protected array $list;

        public function __construct($params)
        {
            parent::__construct($params);
            $this->title = 'Изображение';
        }

        public function __invoke()
        {
            $id = $this->params['id'];
            if (!is_numeric($id)) {
                Relocator::deadend(400); exit();
            }

            $this->list = glob(Config::getInstance()->IMG_PATH . "*.{jpg,jpeg}", GLOB_BRACE);
            $this->content = $this->page->assign('list', $this->list)->assign('id', $id)->render('image');

            parent::__invoke(); // TODO: Change the autogenerated stub
        }

    }
