<?php

    namespace App\classes\controllers;

    use App\classes\abstract\Controller;
    use App\classes\Config;
    use App\classes\models\User;
    use App\classes\utility\ErrorInspectorUser;
    use App\classes\View;

    class Registration extends Controller
    {
//        TODO решить, как именно лучше реализовать вывод ошибок при регистрации (все сразу или сперва только ошибки незаполненных форм)
        protected string $title = 'Регистрация', $content = 'PAGE NOT FOUND!';
        protected User $candidate;

        public function checkUser() : void
        {
            if ($this->user->exist()) {
                header('Location: '. Config::getInstance()->BASE_URL);
                die();
            }
        }

        public function setFields() : void
        {
            $keys = array_keys($_POST);
            $fields = extractFields($keys,$_POST);

            foreach ($fields as $index => &$field) {
                if ($index !== 'password1' || $index !== 'password2') {
                    $fields[$index] = val($field);
                    $userMethod = 'set' . ucfirst($index);
                    if (method_exists($this->candidate, $userMethod)) {
                        $this->candidate->$userMethod($fields[$index]);
                    }
                }
            }
            unset($field);

            $this->candidate->setPasswords($fields['password1'], $fields['password2']);
            $errors = $this->candidate->checkData()->getErrorsContainer()->getData();
            $this->errors->addArray($errors);

            if ($this->errors->isEmpty()) {
                $this->candidate->makeHash();
                $this->candidate->save();
                header('Location: '. Config::getInstance()->BASE_URL);
            }
        }

        public function __invoke()
        {
            $this->checkUser();
            $this->candidate = new User(new ErrorInspectorUser());
            if ('POST' === $_SERVER['REQUEST_METHOD']) {
                $this->setFields();
            }

            $this->content = $this->page->assign('candidate', $this->candidate)->assign('errors', $this->errors)->render('registration');
            parent::__invoke(); // TODO: Change the autogenerated stub
        }
    }
    //TODO -
    // 4. отправить письмо с ключом на почтовый ящик
    // 5. после ввода ключа - пользователь является подтвержденным
